### ISSUE TITLE
Add non-minified compiled version

### ISSUE THREAD

**Issue by gunta** [fastly/epoch#138]
Hi! 

Would it be possible to also add a non-minified compiled version of `epoch.js`?
It will help for debugging.

Thank you!

**Comment by rsandor** [comment]
@gunta - If you clone the repository and follow the build instructions you can get ahold of a non-minifed version (the cakefile will build and store one in the `js/epoch/` directory. Keeping a non-packaged version in the repository was something we considered, but ultimately rejected because we found it to be less than elegant.
