### ISSUE TITLE
Legends and Labels Support

### ISSUE THREAD

**Issue by rsandor** [fastly/epoch#2]
Need a good and elegant way to handle legends and labels on charts.

**Comment by tarelli** [comment]
In my opinion the reason why it would be useful to have as part of the library is that otherwise a lot of people will end up adding it themselves rewriting the same code independently. Also if you do a good job and you want colours to match what's in the plotting, tooltips to show longer names, options to show the labels in different places, etc. it starts being a non negligible effort.

**Comment by dmitry** [comment]
I agree with @tarelli :+1:

**Comment by rsandor** [comment]
@tarelli - Sounds like you have a good idea of how it might work. Want to code it up and send a PR?

**Comment by riskypathak** [comment]
I need this today... Any update whether this is implemented or not??
